using System.Collections.Generic;

namespace KabalistusCommons.Isaac {
    public class Items {
        public static readonly List<Item> RebirthItems = new List<Item>() {
            new Item("The Sad Onion", 1),
            new Item("The Inner Eye", 2),
            new Item("Spoon Bender", 3),
            new Item("Cricket's Head", 4),
            new Item("My Reflection", 5),
            new Item("Number One", 6),
            new Item("Blood of the Martyr", 7),
            new Item("Brother Bobby", 8),
            new Item("Skatole", 9),
            new Item("Halo of Flies", 10),
            new Item("1UP", 11),
            new Item("Magic Mushroom", 12),
            new Item("The Virus", 13),
            new Item("Roid Rage", 14),
            new Item("<3", 15),
            new Item("Raw Liver", 16),
            new Item("Skeleton Key", 17),
            new Item("A Dollar", 18),
            new Item("Boom!", 19),
            new Item("Transcendence", 20),
            new Item("The Compass", 21),
            new Item("Lunch", 22),
            new Item("Dinner", 23),
            new Item("Dessert", 24),
            new Item("Breakfast", 25),
            new Item("Rotten Meat", 26),
            new Item("Wooden Spoon", 27),
            new Item("The Belt", 28),
            new Item("Mom's Underwear", 29),
            new Item("Mom's Heels", 30),
            new Item("Mom's Lipstick", 31),
            new Item("Wire Coat Hanger", 32),
            new Item("The Bible", 33),
            new Item("The Book of Belial", 34),
            new Item("The Necronomicon", 35),
            new Item("The Poop", 36),
            new Item("Mr. Boom", 37),
            new Item("Tammy's Head", 38),
            new Item("Mom's Bra", 39),
            new Item("Kamikaze", 40),
            new Item("Mom's Pad", 41),
            new Item("Bob's Rotten Head", 42),
            new Item("Teleport", 44),
            new Item("Yum Heart", 45),
            new Item("Lucky Foot", 46),
            new Item("Doctor's Remote", 47),
            new Item("Cupid's Arrow", 48),
            new Item("Shoop Da Whoop", 49),
            new Item("Steven", 50),
            new Item("Pentagram", 51),
            new Item("Dr. Fetus", 52),
            new Item("Magneto", 53),
            new Item("Treasure Map", 54),
            new Item("Mom's Eye", 55),
            new Item("Lemon Mishap", 56),
            new Item("Distant Admiration", 57),
            new Item("Book of Shadows", 58),
            new Item("The Ladder", 60),
            new Item("Charm of the Vampire", 62),
            new Item("The Battery", 63),
            new Item("Steam Sale", 64),
            new Item("Anarchist's Cookbook", 65),
            new Item("The Hourglass", 66),
            new Item("Sister Maggy", 67),
            new Item("Technology", 68),
            new Item("Chocolate Milk", 69),
            new Item("Growth Hormones", 70),
            new Item("Mini Mush", 71),
            new Item("Rosary", 72),
            new Item("Cube of Meat", 73),
            new Item("A Quarter", 74),
            new Item("PhD", 75),
            new Item("X-Ray Vision", 76),
            new Item("My Little Unicorn", 77),
            new Item("Book of Revelations", 78),
            new Item("The Mark", 79),
            new Item("The Pact", 80),
            new Item("Dead Cat", 81),
            new Item("Lord of the Pit", 82),
            new Item("The Nail", 83),
            new Item("We Need To Go Deeper", 84),
            new Item("Deck of Cards", 85),
            new Item("Monstro's Tooth", 86),
            new Item("Loki's Horns", 87),
            new Item("Little Chubby", 88),
            new Item("Spider Bite", 89),
            new Item("The Small Rock", 90),
            new Item("Spelunker Hat", 91),
            new Item("Super Bandage", 92),
            new Item("The Gamekid", 93),
            new Item("Sack of Pennies", 94),
            new Item("Robo-Baby", 95),
            new Item("Little C.H.A.D.", 96),
            new Item("The Book of Sin", 97),
            new Item("The Relic", 98),
            new Item("Little Gish", 99),
            new Item("Little Steven", 100),
            new Item("The Halo", 101),
            new Item("Mom's Bottle of Pills", 102),
            new Item("The Common Cold", 103),
            new Item("The Parasite", 104),
            new Item("The D6", 105),
            new Item("Mr. Mega", 106),
            new Item("Pinking Shears", 107),
            new Item("The Wafer", 108),
            new Item("Money = Power", 109),
            new Item("Mom's Contacts", 110),
            new Item("The Bean", 111),
            new Item("Guardian Angel", 112),
            new Item("Demon Baby", 113),
            new Item("Mom's Knife", 114),
            new Item("Ouija Board", 115),
            new Item("9 Volt", 116),
            new Item("Dead Bird", 117),
            new Item("Brimstone", 118),
            new Item("Blood Bag", 119),
            new Item("Odd Mushroom (Thin)", 120),
            new Item("Odd Mushroom (Thick)", 121),
            new Item("Whore of Babylon", 122),
            new Item("Monster Manual", 123),
            new Item("Dead Sea Scrolls", 124),
            new Item("Bobby - Bomb", 125),
            new Item("Razor Blade", 126),
            new Item("Forget Me Now", 127),
            new Item("Forever Alone", 128),
            new Item("Bucket of Lard", 129),
            new Item("A Pony", 130),
            new Item("Bomb Bag", 131),
            new Item("A Lump of Coal", 132),
            new Item("Guppy's Paw", 133),
            new Item("Guppy's Tail", 134),
            new Item("IV Bag", 135),
            new Item("Best Friend", 136),
            new Item("Remote Detonator", 137),
            new Item("Stigmata", 138),
            new Item("Mom's Purse", 139),
            new Item("Bob's Curse", 140),
            new Item("Pageant Boy", 141),
            new Item("Scapular", 142),
            new Item("Speed Ball", 143),
            new Item("Bum Friend", 144),
            new Item("Guppy's Head", 145),
            new Item("Prayer Card", 146),
            new Item("Notched Axe", 147),
            new Item("Infestation", 148),
            new Item("Ipecac", 149),
            new Item("Tough Love", 150),
            new Item("The Mulligan", 151),
            new Item("Technology 2", 152),
            new Item("Mutant Spider", 153),
            new Item("Chemical Peel", 154),
            new Item("The Peeper", 155),
            new Item("Habit", 156),
            new Item("Bloody Lust", 157),
            new Item("Crystal Ball", 158),
            new Item("Spirit of the Night", 159),
            new Item("Crack The Sky", 160),
            new Item("Ankh", 161),
            new Item("Celtic Cross", 162),
            new Item("Ghost Baby", 163),
            new Item("The Candle", 164),
            new Item("Cat-O-Nine-Tails", 165),
            new Item("D20", 166),
            new Item("Harlequin Baby", 167),
            new Item("Epic Fetus", 168),
            new Item("Polyphemus", 169),
            new Item("Daddy Longlegs", 170),
            new Item("Spider Butt", 171),
            new Item("Sacrificial Dagger", 172),
            new Item("Mitre", 173),
            new Item("Rainbow Baby", 174),
            new Item("Dad's Key", 175),
            new Item("Stem Cells", 176),
            new Item("Portable Slot", 177),
            new Item("Holy Water", 178),
            new Item("Fate", 179),
            new Item("The Black Bean", 180),
            new Item("White Pony", 181),
            new Item("Sacred Heart", 182),
            new Item("Toothpicks", 183),
            new Item("Holy Grail", 184),
            new Item("Dead Dove", 185),
            new Item("Blood Rights", 186),
            new Item("Guppy's Hairball", 187),
            new Item("Abel", 188),
            new Item("SMB Super Fan", 189),
            new Item("Pyro", 190),
            new Item("3 Dollar Bill", 191),
            new Item("Telepathy for Dummies", 192),
            new Item("MEAT!", 193),
            new Item("Magic 8 Ball", 194),
            new Item("Mom's Coin Purse", 195),
            new Item("Squeezy", 196),
            new Item("Jesus Juice", 197),
            new Item("Box", 198),
            new Item("Mom's Key", 199),
            new Item("Mom's Eyeshadow", 200),
            new Item("Iron Bar", 201),
            new Item("Midas Touch", 202),
            new Item("Humbleing Bundle", 203),
            new Item("Fanny pack", 204),
            new Item("Sharp plug", 205),
            new Item("The Guillotine", 206),
            new Item("Ball of Bandages", 207),
            new Item("Champion Belt", 208),
            new Item("Butt Bombs", 209),
            new Item("Gnawed Leaf", 210),
            new Item("Spiderbaby", 211),
            new Item("Guppy's Collar", 212),
            new Item("Lost Contact", 213),
            new Item("Anemic", 214),
            new Item("Goat Head", 215),
            new Item("Ceremonial Robes", 216),
            new Item("Mom's Wig", 217),
            new Item("Placenta", 218),
            new Item("Old Bandage", 219),
            new Item("Sad Bombs", 220),
            new Item("Rubber Cement", 221),
            new Item("Anti-Gravity", 222),
            new Item("Pyromaniac", 223),
            new Item("Cricket's Body", 224),
            new Item("Gimpy", 225),
            new Item("Black Lotus", 226),
            new Item("Piggy Bank", 227),
            new Item("Mom's Perfume:", 228),
            new Item("Monstro's Lung", 229),
            new Item("Abaddon", 230),
            new Item("Ball of Tar", 231),
            new Item("Stop Watch", 232),
            new Item("Tiny Planet", 233),
            new Item("Infestation 2", 234),
            new Item("E. Coli", 236),
            new Item("Death's Touch", 237),
            new Item("Key Piece #1", 238),
            new Item("Key Piece #2", 239),
            new Item("Experimental Treatment", 240),
            new Item("Contract From Below", 241),
            new Item("Infamy", 242),
            new Item("Trinity Shield", 243),
            new Item("Tech.5", 244),
            new Item("20/20", 245),
            new Item("Blue Map", 246),
            new Item("BFFS!", 247),
            new Item("Hive Mind", 248),
            new Item("There's Options", 249),
            new Item("Bogo Bombs", 250),
            new Item("Starter Deck", 251),
            new Item("Little Baggy", 252),
            new Item("Magic Scab", 253),
            new Item("Blood Clot", 254),
            new Item("Screw", 255),
            new Item("Hot Bombs", 256),
            new Item("Fire Mind", 257),
            new Item("Missing No.", 258),
            new Item("Dark Matter", 259),
            new Item("Black Candle", 260),
            new Item("Proptosis", 261),
            new Item("Missing Page 2", 262),
            new Item("Smart Fly", 264),
            new Item("Dry Baby", 265),
            new Item("Juicy Sack", 266),
            new Item("Robo-Baby 2.0", 267),
            new Item("Rotten Baby", 268),
            new Item("Headless Baby", 269),
            new Item("Leech", 270),
            new Item("Mystery Sack", 271),
            new Item("BBF", 272),
            new Item("Bob's Brain", 273),
            new Item("Best Bud", 274),
            new Item("Lil' Brimstone", 275),
            new Item("Isaac's Heart", 276),
            new Item("Lil' Haunt", 277),
            new Item("Dark Bum", 278),
            new Item("Big Fan", 279),
            new Item("Sissy Long Legs", 280),
            new Item("Punching Bag", 281),
            new Item("How To Jump", 282),
            new Item("D100", 283),
            new Item("D4", 284),
            new Item("D10", 285),
            new Item("Blank Card", 286),
            new Item("Book of Secrets", 287),
            new Item("Box of Spiders", 288),
            new Item("Red Candle", 289),
            new Item("The Jar", 290),
            new Item("FLUSH!", 291),
            new Item("The Satanic Bible", 292),
            new Item("Head of Krampus", 293),
            new Item("Butter Bean", 294),
            new Item("Magic Fingers", 295),
            new Item("Converter", 296),
            new Item("Pandora's Box", 297),
            new Item("Unicorn Stump", 298),
            new Item("Taurus", 299),
            new Item("Aries", 300),
            new Item("Cancer", 301),
            new Item("Leo", 302),
            new Item("Virgo", 303),
            new Item("Libra", 304),
            new Item("Scorpio", 305),
            new Item("Sagittarius", 306),
            new Item("Capricorn", 307),
            new Item("Aquarius", 308),
            new Item("Pisces", 309),
            new Item("Eve's Mascara", 310),
            new Item("Judas' Shadow", 311),
            new Item("Maggy's Bow", 312),
            new Item("Holy Mantle", 313),
            new Item("Thunder Thighs", 314),
            new Item("Strange Attractor", 315),
            new Item("Cursed Eye", 316),
            new Item("Mysterious Liquid", 317),
            new Item("Gemini", 318),
            new Item("Cain's Other Eye", 319),
            new Item("???'s Only Friend", 320),
            new Item("Samson's Chains", 321),
            new Item("Mongo Baby", 322),
            new Item("Isaac's Tears", 323),
            new Item("Undefined", 324),
            new Item("Scissors", 325),
            new Item("Breath of Life", 326),
            new Item("The Polaroid", 327),
            new Item("The Negative", 328),
            new Item("The Ludovico Technique", 329),
            new Item("Soy Milk", 330),
            new Item("GodHead", 331),
            new Item("Lazarus' Rags", 332),
            new Item("The Mind", 333),
            new Item("The Body", 334),
            new Item("The Soul", 335),
            new Item("Dead Onion", 336),
            new Item("Broken Watch", 337),
            new Item("Boomerang", 338),
            new Item("Safety Pin", 339),
            new Item("Caffeine Pill", 340),
            new Item("Torn Photo", 341),
            new Item("Blue Cap", 342),
            new Item("Latch Key", 343),
            new Item("Match Book", 344),
            new Item("Synthoil", 345),
            new Item("A Snack", 346)
        };

        public static readonly List<Item> AfterbirthItems = new List<Item>() {
            new Item("Diplopia", 347),
            new Item("Placebo", 348),
            new Item("Wooden Nickel", 349),
            new Item("Toxic Shock", 350),
            new Item("Mega Bean", 351),
            new Item("Glass Cannon", 352),
            new Item("Bomber Boy", 353),
            new Item("Crack Jacks", 354),
            new Item("Mom's Pearls", 355),
            new Item("Car Battery", 356),
            new Item("Box of Friends", 357),
            new Item("The Wiz", 358),
            new Item("8 Inch Nails", 359),
            new Item("Incubus", 360),
            new Item("Fate's Reward", 361),
            new Item("Lil Chest", 362),
            new Item("Sworn Protector", 363),
            new Item("Friend Zone", 364),
            new Item("Lost Fly", 365),
            new Item("Scatter Bombs", 366),
            new Item("Sticky Bombs", 367),
            new Item("Epiphora", 368),
            new Item("Continuum", 369),
            new Item("Mr. Dolly", 370),
            new Item("Curse of The Tower", 371),
            new Item("Charged Baby", 372),
            new Item("Dead Eye", 373),
            new Item("Holy Light!", 374),
            new Item("Host Hat", 375),
            new Item("Restock", 376),
            new Item("Bursting Sack", 377),
            new Item("No. 2", 378),
            new Item("Pupula Duplex", 379),
            new Item("Pay To Play", 380),
            new Item("Eden's Blessing", 381),
            new Item("Friendly Ball", 382),
            new Item("Tear Detonator", 383),
            new Item("Lil Gurdy", 384),
            new Item("Bumbo", 385),
            new Item("D12", 386),
            new Item("Censer", 387),
            new Item("Key Bum", 388),
            new Item("Rune Bag", 389),
            new Item("Seraphim", 390),
            new Item("Betrayal", 391),
            new Item("Zodiac", 392),
            new Item("Serpent's Kiss", 393),
            new Item("Marked", 394),
            new Item("Tech X", 395),
            new Item("Ventricle Razor", 396),
            new Item("Tractor Beam", 397),
            new Item("God's Flesh", 398),
            new Item("Maw of The Void", 399),
            new Item("Spear of Destiny", 400),
            new Item("Explosivo", 401),
            new Item("Chaos", 402),
            new Item("Spider Mod", 403),
            new Item("Farting Baby", 404),
            new Item("GB Bug", 405),
            new Item("D8", 406),
            new Item("Purity", 407),
            new Item("Athame", 408),
            new Item("Empty Vessel", 409),
            new Item("Evil Eye", 410),
            new Item("Lusty Blood", 411),
            new Item("Cambion Conception", 412),
            new Item("Immaculate Conception", 413),
            new Item("More Options", 414),
            new Item("Crown of Light", 415),
            new Item("Deep Pockets", 416),
            new Item("Succubus", 417),
            new Item("Fruit Cake", 418),
            new Item("Teleport 2.0", 419),
            new Item("Black Powder", 420),
            new Item("Kidney Bean", 421),
            new Item("Glowing Hour Glass", 422),
            new Item("Circle of Protection", 423),
            new Item("Sack Head", 424),
            new Item("Night Light", 425),
            new Item("Obsessed Fan", 426),
            new Item("Mine Crafter", 427),
            new Item("PJs", 428),
            new Item("Head of the Keeper", 429),
            new Item("Papa Fly", 430),
            new Item("Multidimensional Baby", 431),
            new Item("Glitter Bombs", 432),
            new Item("My Shadow", 433),
            new Item("Jar of Flies", 434),
            new Item("Lil Loki", 435),
            new Item("Milk!", 436),
            new Item("D7", 437),
            new Item("Binky", 438),
            new Item("Mom's Box", 439),
            new Item("Kidney Stone", 440),
            new Item("Mega Blast", 441)
        };

        public static readonly List<Item> AfterbirthPlusItems = new List<Item>() {
            new Item("Dark Princes Crown", 442),
            new Item("Apple!", 443),
            new Item("Lead Pencil", 444),
            new Item("Dog Tooth", 445),
            new Item("Dead Tooth", 446),
            new Item("Linger Bean", 447),
            new Item("Shard of Glass", 448),
            new Item("Metal Plate", 449),
            new Item("Eye of Greed", 450),
            new Item("Tarot Cloth", 451),
            new Item("Varicose Veins", 452),
            new Item("Compound Fracture", 453),
            new Item("Polydactyly", 454),
            new Item("Dad's Lost Coin", 455),
            new Item("Moldy Bread", 456),
            new Item("Cone Head", 457),
            new Item("Belly Button", 458),
            new Item("Sinus Infection", 459),
            new Item("Glaucoma", 460),
            new Item("Parasitoid", 461),
            new Item("Eye of Belial", 462),
            new Item("Sulfuric Acid", 463),
            new Item("Glyph of Balance", 464),
            new Item("Analog Stick", 465),
            new Item("Contagion", 466),
            new Item("Finger!", 467),
            new Item("Shade", 468),
            new Item("Depression", 469),
            new Item("Hushy", 470),
            new Item("Lil Monstro", 471),
            new Item("King Baby", 472),
            new Item("Big Chubby", 473),
            new Item("Plan C", 475),
            new Item("D1", 476),
            new Item("Void", 477),
            new Item("Pause", 478),
            new Item("Smelter", 479),
            new Item("Compost", 480),
            new Item("Dataminer", 481),
            new Item("Clicker", 482),
            new Item("MaMa Mega!", 483),
            new Item("Wait What?", 484),
            new Item("Crooked Penny", 485),
            new Item("Dull Razor", 486),
            new Item("Potato Peeler", 487),
            new Item("Metronome", 488),
            new Item("D infinity", 489),
            new Item("Eden's Soul", 490),
            new Item("Acid Baby", 491),
            new Item("YO LISTEN!", 492),
            new Item("Adderline", 493),
            new Item("Jacob's Ladder", 494),
            new Item("Ghost Pepper", 495),
            new Item("Euthanasia", 496),
            new Item("Camo Undies", 497),
            new Item("Duality", 498),
            new Item("Eucharist", 499),
            new Item("Sack of Sacks", 500),
            new Item("Greed's Gullet", 501),
            new Item("Large Zit", 502),
            new Item("Little Horn", 503),
            new Item("Brown Nugget", 504),
            new Item("Poke Go", 505),
            new Item("BackStabber", 506),
            new Item("Sharp Straw", 507),
            new Item("Mom's Razor", 508),
            new Item("Bloodshot Eye", 509),
            new Item("Delirious", 510)
        };

        public static readonly List<Item> AntibirthItems = new List<Item>() {
            new Item("Mucormycosis", 1000),
            new Item("2Spooky", 1001),
            new Item("Schoolbag", 1002),
            new Item("Sulfur", 1003),
            new Item("Fortune Cookie", 1004),
            new Item("Eye Sore", 1005),
            new Item("120 Volt", 1006),
            new Item("It Hurts", 1007),
            new Item("Almond Milk", 1008),
            new Item("Rock Bottom", 1009),
            new Item("Enigma Bombs", 1010),
            new Item("A Bar of Soap", 1011),
            new Item("Book of Despair", 1012),
            new Item("D12", 1013),
            new Item("Paschal Candle", 1014),
            new Item("Bowl of Tears", 1015),
            new Item("Blood Oath", 1016),
            new Item("Playdoh Cookie", 1017),
            new Item("Orphan Socks", 1018),
            new Item("Eye of the Occult", 1019),
            new Item("Immaculate Heart", 1020),
            new Item("Monstrance", 1021),
            new Item("The Intruder", 1022),
            new Item("Dirty Mind", 1023),
            new Item("Damocles", 1024),
            new Item("Free Lemonade", 1025),
            new Item("Spirit Sword", 1026),
            new Item("Red Key", 1027),
            new Item("Psy Fly", 1028),
            new Item("Black Mushroom", 1029),
            new Item("Rocket in a Jar", 1030),
            new Item("Book of Virtues", 1031),
            new Item("Alabaster Box", 1032),
            new Item("Jacob's Ladder", 1033),
            new Item("Menorah", 1034),
            new Item("Sol", 1035),
            new Item("Luna", 1036),
            new Item("Mercurius", 1037),
            new Item("Venus", 1038),
            new Item("Terra", 1039),
            new Item("Mars", 1040),
            new Item("Saturnus", 1042),
            new Item("Uranus", 1043),
            new Item("Pluto", 1045),
            new Item("Voodoo Head", 1046),
            new Item("Eye Drops", 1047),
            new Item("Act of Contrition", 1048),
            new Item("Member Card", 1049),
            new Item("Battery Pack", 1050),
            new Item("Mom's Bracelet", 1051),
            new Item("The Scooper", 1052),
            new Item("Oculus Rift", 1053),
            new Item("Boiled Baby", 1054),
            new Item("Freezer Baby", 1055),
            new Item("Eternal D6", 1056),
            new Item("Bird Cage", 1057),
            new Item("Donkey Jawbone", 1058),
            new Item("Lost Soul", 1059),
            new Item("Blood Bombs", 1061),
            new Item("Lil' Dumpy", 1062),
            new Item("Bird's Eye", 1063),
            new Item("Lodestone", 1064),
            new Item("Rotten Tomato", 1065),
            new Item("Birthright", 1066),
            new Item("Voodoo Pin", 1067),
            new Item("Red Stew", 1068),
            new Item("Sausage", 1069),
            new Item("Sharp Key", 1070),
            new Item("Booster Pack", 1071),
            new Item("Mega Mush", 1072),
            new Item("Knife Piece 1", 1073),
            new Item("Knife Piece 2", 1074),
            new Item("Knife Piece 3", 1075),
            new Item("Bot Fly", 1076),
            new Item("Meat Cleaver", 1078),
            new Item("Evil Charm", 1079),
            new Item("Stone Bombs", 1080),
            new Item("Stitches", 1082),
            new Item("R Key", 1083),
            new Item("Knockout Drops", 1084),
            new Item("Eraser", 1085),
            new Item("Yuck Heart", 1086),
            new Item("Akeldama", 1088),
            new Item("Magic Skin", 1089),
            new Item("Revelation", 1090),
            new Item("Consolation Prize", 1091),
            new Item("Tinytoma", 1092)
        };
    }
}
