using System.Collections.Generic;

namespace KabalistusCommons.Isaac {
    public class Pills {
        public static Dictionary<int, Item> AllPills = new Dictionary<int, Item>() {
            {0, new Item("Bad Gas", 0)},
            {1, new Item("Bad Trip", 1)},
            {2, new Item("Balls of Steel", 2)},
            {3, new Item("Bombs Are Key", 3)},
            {4, new Item("Explosive Diarrhea", 4)},
            {5, new Item("Full Health", 5)},
            {6, new Item("Health Down", 6)},
            {7, new Item("Health Up", 7)},
            {8, new Item("I Found Pills", 8)},
            {9, new Item("Puberty", 9)},
            {10, new Item("Pretty Fly", 10)},
            {11, new Item("Range Down", 11)},
            {12, new Item("Range Up", 12)},
            {13, new Item("Speed Down", 13)},
            {14, new Item("Speed Up", 14)},
            {15, new Item("Tears Down", 15)},
            {16, new Item("Tears Up", 16)},
            {17, new Item("Luck Down", 17)},
            {18, new Item("Luck Up", 18)},
            {19, new Item("Telepills", 19)},
            {20, new Item("48 Hour Energy!", 20)},
            {21, new Item("Hematemesis", 21)},
            {22, new Item("Paralysis", 22)},
            {23, new Item("I can see forever!", 23)},
            {24, new Item("Pheromones", 24)},
            {25, new Item("Amnesia", 25)},
            {26, new Item("Lemon Party", 26)},
            {27, new Item("R U a Wizard?", 27)},
            {28, new Item("Percs!", 28)},
            {29, new Item("Addicted!", 29)},
            {30, new Item("Re-Lax", 30)},
            {31, new Item("???", 31)},
            {32, new Item("One makes you larger", 32)},
            {33, new Item("One makes you small", 33)},
            {34, new Item("Infested!", 34)},
            {35, new Item("Infested?", 35)},
            {36, new Item("Power Pill!", 36)},
            {37, new Item("Retro Vision", 37)},
            {38, new Item("Friends Till The End!", 38)},
            {39, new Item("X-Lax", 39)},
            {40, new Item("Something's wrong...", 40)},
            {41, new Item("I'm Drowsy...", 41)},
            {42, new Item("I'm Excited!!!", 42)},
            {43, new Item("Gulp!", 43)},
            {44, new Item("Horf!", 44)},
            {45, new Item("Feels like I'm walking on sunshine!", 45)},
            {46, new Item("Vurp!", 46)},
        };
    }
}
