using System.Collections.Generic;

namespace KabalistusCommons.Isaac {
    public class Trinkets {
        public static readonly Dictionary<int, Trinket> AllTrinkets = new Dictionary<int, Trinket>() {
            {1, new Trinket("Swallowed Penny", 1)},
            {2, new Trinket("Petrified Poop", 2)},
            {3, new Trinket("AAA Battery", 3)},
            {4, new Trinket("Broken Remote", 4)},
            {5, new Trinket("Purple Heart", 5)},
            {6, new Trinket("Broken Magnet", 6)},
            {7, new Trinket("Rosary Bead", 7)},
            {8, new Trinket("Cartridge", 8)},
            {9, new Trinket("Pulse Worm", 9)},
            {10, new Trinket("Wiggle Worm", 10)},
            {11, new Trinket("Ring Worm", 11)},
            {12, new Trinket("Flat Worm", 12)},
            {13, new Trinket("Store Credit", 13)},
            {14, new Trinket("Callus", 14)},
            {15, new Trinket("Lucky Rock", 15)},
            {16, new Trinket("Mom's Toenail", 16)},
            {17, new Trinket("Black Lipstick", 17)},
            {18, new Trinket("Bible Tract", 18)},
            {19, new Trinket("Paper Clip", 19)},
            {20, new Trinket("Monkey Paw", 20)},
            {21, new Trinket("Mysterious Paper", 21)},
            {22, new Trinket("Daemon's Tail", 22)},
            {23, new Trinket("Missing Poster", 23)},
            {24, new Trinket("Butt Penny", 24)},
            {25, new Trinket("Mysterious Candy", 25)},
            {26, new Trinket("Hook Worm", 26)},
            {27, new Trinket("Whip Worm", 27)},
            {28, new Trinket("Broken Ankh", 28)},
            {29, new Trinket("Fish Head", 29)},
            {30, new Trinket("Pinky Eye", 30)},
            {31, new Trinket("Push Pin", 31)},
            {32, new Trinket("Liberty Cap", 32)},
            {33, new Trinket("Umbilical Cord", 33)},
            {34, new Trinket("Child's Heart", 34)},
            {35, new Trinket("Curved Horn", 35)},
            {36, new Trinket("Rusted Key", 36)},
            {37, new Trinket("Goat Hoof", 37)},
            {38, new Trinket("Mom's Pearl", 38)},
            {39, new Trinket("Cancer", 39)},
            {40, new Trinket("Red Patch", 40)},
            {41, new Trinket("Match Stick", 41)},
            {42, new Trinket("Lucky Toe", 42)},
            {43, new Trinket("Cursed Skull", 43)},
            {44, new Trinket("Safety Cap", 44)},
            {45, new Trinket("Ace of Spades", 45)},
            {46, new Trinket("Isaac's Fork", 46)},
            {48, new Trinket("A Missing Page", 48)},
            {49, new Trinket("Bloody Penny", 49)},
            {50, new Trinket("Burnt Penny", 50)},
            {51, new Trinket("Flat Penny", 51)},
            {52, new Trinket("Counterfeit Penny", 52)},
            {53, new Trinket("Tick", 53)},
            {54, new Trinket("Isaac's Head", 54)},
            {55, new Trinket("Maggy's Faith", 55)},
            {56, new Trinket("Judas' Tongue", 56)},
            {57, new Trinket("???'s Soul", 57)},
            {58, new Trinket("Samson's Lock", 58)},
            {59, new Trinket("Cain's Eye", 59)},
            {60, new Trinket("Eve's Bird Foot", 60)},
            {61, new Trinket("The Left Hand", 61)},
            {62, new Trinket("Shiny Rock", 62)},
            {63, new Trinket("Safety Scissors", 63)},
            {64, new Trinket("Rainbow Worm", 64)},
            {65, new Trinket("Tape Worm", 65)},
            {66, new Trinket("Lazy Worm", 66)},
            {67, new Trinket("Cracked Dice", 67)},
            {68, new Trinket("Super Magnet", 68)},
            {69, new Trinket("Faded Polaroid", 69)},
            {70, new Trinket("Louse", 70)},
            {71, new Trinket("Bob's Bladder", 71)},
            {72, new Trinket("Watch Battery", 72)},
            {73, new Trinket("Blasting Cap", 73)},
            {74, new Trinket("Stud Finder", 74)},
            {75, new Trinket("Error", 75)},
            {76, new Trinket("Poker Chip", 76)},
            {77, new Trinket("Blister", 77)},
            {78, new Trinket("Second Hand", 78)},
            {79, new Trinket("Endless Nameless", 79)},
            {80, new Trinket("Black Feather", 80)},
            {81, new Trinket("Blind Rage", 81)},
            {82, new Trinket("Golden Horse Shoe", 82)},
            {83, new Trinket("Store Key", 83)},
            {84, new Trinket("Rib of Greed", 84)},
            {85, new Trinket("Karma", 85)},
            {86, new Trinket("Lil Larva", 86)},
            {87, new Trinket("Mom's Locket", 87)},
            {88, new Trinket("NO!", 88)},
            {89, new Trinket("Child Leash", 89)},
            {90, new Trinket("Brown Cap", 90)},
            {91, new Trinket("Meconium", 91)},
            {92, new Trinket("Cracked Crown", 92)},
            {93, new Trinket("Used Diaper", 93)},
            {94, new Trinket("Fish Tail", 94)},
            {95, new Trinket("Black Tooth", 95)},
            {96, new Trinket("Ouroboros Worm", 96)},
            {97, new Trinket("Tonsil", 97)},
            {98, new Trinket("Nose Goblin", 98)},
            {99, new Trinket("Super Ball", 99)},
            {100, new Trinket("Vibrant Bulb", 100)},
            {101, new Trinket("Dim Bulb", 101)},
            {102, new Trinket("Fragmented Card", 102)},
            {103, new Trinket("Equality!", 103)},
            {104, new Trinket("Wish Bone", 104)},
            {105, new Trinket("Bag Lunch", 105)},
            {106, new Trinket("Lost Cork", 106)},
            {107, new Trinket("Crow Heart", 107)},
            {108, new Trinket("Walnut", 108)},
            {109, new Trinket("Duct Tape", 109)},
            {110, new Trinket("Silver Dollar", 110)},
            {111, new Trinket("Bloody Crown", 111)},
            {112, new Trinket("Pay To Win", 112)},
            {113, new Trinket("Locust of Wrath", 113)},
            {114, new Trinket("Locust of Pestilence", 114)},
            {115, new Trinket("Locust of Famine", 115)},
            {116, new Trinket("Locust of Death", 116)},
            {117, new Trinket("Locust of Conquest", 117)},
            {118, new Trinket("Bat Wing", 118)},
            {119, new Trinket("Stem Cell", 119)}
        };
    }
}
