using System.Collections.Generic;

namespace KabalistusCommons.Isaac {
    public class Trinkets {
        public static readonly Dictionary<int, Item> AllTrinkets = new Dictionary<int, Item>() {
            {1, new Item("Swallowed Penny", 1)},
            {2, new Item("Petrified Poop", 2)},
            {3, new Item("AAA Battery", 3)},
            {4, new Item("Broken Remote", 4)},
            {5, new Item("Purple Heart", 5)},
            {6, new Item("Broken Magnet", 6)},
            {7, new Item("Rosary Bead", 7)},
            {8, new Item("Cartridge", 8)},
            {9, new Item("Pulse Worm", 9)},
            {10, new Item("Wiggle Worm", 10)},
            {11, new Item("Ring Worm", 11)},
            {12, new Item("Flat Worm", 12)},
            {13, new Item("Store Credit", 13)},
            {14, new Item("Callus", 14)},
            {15, new Item("Lucky Rock", 15)},
            {16, new Item("Mom's Toenail", 16)},
            {17, new Item("Black Lipstick", 17)},
            {18, new Item("Bible Tract", 18)},
            {19, new Item("Paper Clip", 19)},
            {20, new Item("Monkey Paw", 20)},
            {21, new Item("Mysterious Paper", 21)},
            {22, new Item("Daemon's Tail", 22)},
            {23, new Item("Missing Poster", 23)},
            {24, new Item("Butt Penny", 24)},
            {25, new Item("Mysterious Candy", 25)},
            {26, new Item("Hook Worm", 26)},
            {27, new Item("Whip Worm", 27)},
            {28, new Item("Broken Ankh", 28)},
            {29, new Item("Fish Head", 29)},
            {30, new Item("Pinky Eye", 30)},
            {31, new Item("Push Pin", 31)},
            {32, new Item("Liberty Cap", 32)},
            {33, new Item("Umbilical Cord", 33)},
            {34, new Item("Child's Heart", 34)},
            {35, new Item("Curved Horn", 35)},
            {36, new Item("Rusted Key", 36)},
            {37, new Item("Goat Hoof", 37)},
            {38, new Item("Mom's Pearl", 38)},
            {39, new Item("Cancer", 39)},
            {40, new Item("Red Patch", 40)},
            {41, new Item("Match Stick", 41)},
            {42, new Item("Lucky Toe", 42)},
            {43, new Item("Cursed Skull", 43)},
            {44, new Item("Safety Cap", 44)},
            {45, new Item("Ace of Spades", 45)},
            {46, new Item("Isaac's Fork", 46)},
            {48, new Item("A Missing Page", 48)},
            {49, new Item("Bloody Penny", 49)},
            {50, new Item("Burnt Penny", 50)},
            {51, new Item("Flat Penny", 51)},
            {52, new Item("Counterfeit Penny", 52)},
            {53, new Item("Tick", 53)},
            {54, new Item("Isaac's Head", 54)},
            {55, new Item("Maggy's Faith", 55)},
            {56, new Item("Judas' Tongue", 56)},
            {57, new Item("???'s Soul", 57)},
            {58, new Item("Samson's Lock", 58)},
            {59, new Item("Cain's Eye", 59)},
            {60, new Item("Eve's Bird Foot", 60)},
            {61, new Item("The Left Hand", 61)},
            {62, new Item("Shiny Rock", 62)},
            {63, new Item("Safety Scissors", 63)},
            {64, new Item("Rainbow Worm", 64)},
            {65, new Item("Tape Worm", 65)},
            {66, new Item("Lazy Worm", 66)},
            {67, new Item("Cracked Dice", 67)},
            {68, new Item("Super Magnet", 68)},
            {69, new Item("Faded Polaroid", 69)},
            {70, new Item("Louse", 70)},
            {71, new Item("Bob's Bladder", 71)},
            {72, new Item("Watch Battery", 72)},
            {73, new Item("Blasting Cap", 73)},
            {74, new Item("Stud Finder", 74)},
            {75, new Item("Error", 75)},
            {76, new Item("Poker Chip", 76)},
            {77, new Item("Blister", 77)},
            {78, new Item("Second Hand", 78)},
            {79, new Item("Endless Nameless", 79)},
            {80, new Item("Black Feather", 80)},
            {81, new Item("Blind Rage", 81)},
            {82, new Item("Golden Horse Shoe", 82)},
            {83, new Item("Store Key", 83)},
            {84, new Item("Rib of Greed", 84)},
            {85, new Item("Karma", 85)},
            {86, new Item("Lil Larva", 86)},
            {87, new Item("Mom's Locket", 87)},
            {88, new Item("NO!", 88)},
            {89, new Item("Child Leash", 89)},
            {90, new Item("Brown Cap", 90)},
            {91, new Item("Meconium", 91)},
            {92, new Item("Cracked Crown", 92)},
            {93, new Item("Used Diaper", 93)},
            {94, new Item("Fish Tail", 94)},
            {95, new Item("Black Tooth", 95)},
            {96, new Item("Ouroboros Worm", 96)},
            {97, new Item("Tonsil", 97)},
            {98, new Item("Nose Goblin", 98)},
            {99, new Item("Super Ball", 99)},
            {100, new Item("Vibrant Bulb", 100)},
            {101, new Item("Dim Bulb", 101)},
            {102, new Item("Fragmented Card", 102)},
            {103, new Item("Equality!", 103)},
            {104, new Item("Wish Bone", 104)},
            {105, new Item("Bag Lunch", 105)},
            {106, new Item("Lost Cork", 106)},
            {107, new Item("Crow Heart", 107)},
            {108, new Item("Walnut", 108)},
            {109, new Item("Duct Tape", 109)},
            {110, new Item("Silver Dollar", 110)},
            {111, new Item("Bloody Crown", 111)},
            {112, new Item("Pay To Win", 112)},
            {113, new Item("Locust of Wrath", 113)},
            {114, new Item("Locust of Pestilence", 114)},
            {115, new Item("Locust of Famine", 115)},
            {116, new Item("Locust of Death", 116)},
            {117, new Item("Locust of Conquest", 117)},
            {118, new Item("Bat Wing", 118)},
            {119, new Item("Stem Cell", 119)}
        };
    }
}
